[build]
  command = "npm install && cp server.js netlify/functions/server.js && cp languages.json netlify/functions/languages.json && cp workflow.json netlify/functions/workflow.json"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "18"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@kontent-ai/management-sdk"]

[dev]
  port = 8888
  publish = "public"
  functions = "netlify/functions"
  envFiles = [".env"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
